## Homework 1
Gabrial Erismann

In [1]:
import numpy as np

## Exercise 1

*a* and *b* are first entered as Python `lists` which are an ordered collection of objects. They are then turned into numpy `arrays` which can be seen as matrices of dimension (1,3) or a row vector.

In [2]:
a =  [2,3,4]
b = [-1,3,0]
print(type(a))

a_ = np.array(a)
b_ = np.array(b)
print(type(a_))

<class 'list'>
<class 'numpy.ndarray'>


## Exercise 2
In numpy the transpose of a 1d array is the same 1d array. In order to see the transpose, one should make a matrix *c* using *a* and *b* as rows and then comparing *c* and $c^T$

In [3]:
print(F' b_ is an matrix of shape: \t {b_.shape} \n b_ transpose is a matrix of shape: \t {(b_.transpose()).shape}')
print(b_)

 b_ is an matrix of shape: 	 (3,) 
 b_ transpose is a matrix of shape: 	 (3,)
[-1  3  0]


In [4]:
c = np.array((a_,b_))
print(F' c is an matrix of shape: {c.shape} \n c transpose is a matrix of shape: {(c.transpose()).shape}')
print( F' c is \n {c} \n and c transpose is \n {c.transpose()}')

 c is an matrix of shape: (2, 3) 
 c transpose is a matrix of shape: (3, 2)
 c is 
 [[ 2  3  4]
 [-1  3  0]] 
 and c transpose is 
 [[ 2 -1]
 [ 3  3]
 [ 4  0]]


## Exercise 3

The difference between `t(a)*b` and `t(a)%*%b` in R is the difference beteen `a.transpose()*b` and `np.dot(a_,b_) or np.outer(a_,b_)` in numpy, that is to say the difference between pairwise multiplication and matrix (dot) multiplication resulting in either in a 1x1 matrix (np.dot) or in a 3x3 matrix (np.outer)

In [5]:
# c = a + b
c = a_ + b_
print(c)

[1 6 4]


In [10]:
# c = transpose (d1,d2,d3)
c = (a_*b_).transpose()
print(F'pairwise multiplication is {c}')
c = np.dot(a_,b_)
print(F'dot product a dot b_transpose is {c}')
c = np.outer(a_,b_)
print(F'dot product b dot a_transpose is \n{c}')

pairwise multiplication is [-2  9  0]
dot product a dot b_transpose is 7
dot product b dot a_transpose is 
[[-2  6  0]
 [-3  9  0]
 [-4 12  0]]


## Exercise 4

In [7]:
c = (a_[0:2] + b[0:2]).transpose()
print(c)

[1 6]


## Exercise 5

In [8]:
def myfunc(x):
    return np.sqrt(np.square(x) + 2)
x = np.array((-2,0,7))
a = myfunc(x)
print(F'testing f(x): \n {a}')
b = myfunc(a_)
print(F'testing f(a_): \n {b}')

testing f(x): 
 [2.44948974 1.41421356 7.14142843]
testing f(a_): 
 [2.44948974 3.31662479 4.24264069]


## Exercise 6
I don't know but if I had to guess I would say its because True/False can be stored simply as 1/0.

In [9]:
truths = np.array((True,False,True,False,True))
print(F'The created array look like expected {truths} \nand converts to int by multiplying by 1 {truths*1}')

The created array look like expected [ True False  True False  True] 
and converts to int by multiplying by 1 [1 0 1 0 1]
