In [1]:
import numpy as np

# Homework 3
Gabrial Erismann

## Exercise 1

In [2]:
v1 = [-2,1,7,4,6]
v2 = [1,-10,-6,-5,13]
v3 = [7,-6,-16,8,5]
v4 = [4,-5,8,0,7]
v5 = [6,13,5,7,10]

In [3]:
a = np.array((v1,v2,v3,v4,v5))
a

array([[ -2,   1,   7,   4,   6],
       [  1, -10,  -6,  -5,  13],
       [  7,  -6, -16,   8,   5],
       [  4,  -5,   8,   0,   7],
       [  6,  13,   5,   7,  10]])

## Exercise 2
1) Symmetric as $a_{i,j} = a_{j,i} \,\,\forall\,\,a_{i,j},a_{j,i}\,\in \,\,A $
2) Nonsingular as $rank(A) = 5$ and $A$ has 5 columns, thus $A$ is full rank.
3) As stated above.
4) Not positive definite as not all eigenvalues > 0
5) Not orthogonal as $A^TA \neq I$

In [4]:
# 1 check transpose
answer = a == a.transpose()
np.all(answer)

True

In [5]:
# 2 & 3 check the rank
answer = np.linalg.matrix_rank(a)
answer

5

In [6]:
#4 check if positive definite
def check_posdef(x):
    return np.linalg.eigvals(a)>0
np.all(check_posdef(a))

False

In [7]:
# 5 check orthogonality
np.all(np.round(np.dot(a.transpose(),a)) == np.identity)

False

## Exercise 3

1) $CC^T = I$
2) Since $A$ is a symmetric matrix as shown above and since $\lambda_{i} \neq \lambda_{j} \forall \lambda$, the matrix $C$ defined by the eigenvectors of $A$ is orthogonal. Thus, by orthogonality, $C^T = C^{-1}$
3) The inverse of $C$ is $C^T$ as demonstrated by 1) and 2)

In [8]:
# demonstrate CCtranpose = I
c = np.linalg.eig(a)[1]
c_ = c.transpose()
result = np.round(np.dot(c,c_))
result

array([[ 1.,  0.,  0., -0., -0.],
       [ 0.,  1., -0.,  0., -0.],
       [ 0., -0.,  1.,  0., -0.],
       [-0.,  0.,  0.,  1.,  0.],
       [-0., -0., -0.,  0.,  1.]])

# Exercise 4

One way to get the inverse matrix is to use the eigendecomposition that is, $$A^{-1} = C\Lambda^{-1}C^{-1}$$

where $\Lambda_{i,i} =  \lambda_{i}$, and $C$ is the matrix whose rows are formed by the corresponding eigenvectors of $A$. Here the inverse matrices are given simply by the already calculated eigenvalues and eigenvectors. First $\Lambda^{-1}_{i,j} = 1/\lambda_i \,\, \forall i=j, \,\,and \,\,\Lambda^{-1}_{i,j} = 0 \,\,\forall \,\, i \neq j$ and second $C^{-1}= C^T$ as shown in exercise 3.

In [9]:
# get inverse diagonal matrix of eigenvalues
diag = np.diag(1/(np.linalg.eig(a)[0]))

# calculate spectral decompostion to identify inverse
inverse = np.dot(np.dot(c,diag),c_)

In [10]:
inverse

array([[-0.13426891, -0.02967414,  0.01689683,  0.10638671,  0.03621862],
       [-0.02967414,  0.01046272, -0.02641489, -0.0531544 ,  0.05461847],
       [ 0.01689683, -0.02641489, -0.01832519,  0.05849126, -0.00758004],
       [ 0.10638671, -0.0531544 ,  0.05849126, -0.00175298, -0.02274985],
       [ 0.03621862,  0.05461847, -0.00758004, -0.02274985,  0.02697974]])

In [11]:
# check answer with numpy's built-in inverse function
np.linalg.inv(a)

array([[-0.13426891, -0.02967414,  0.01689683,  0.10638671,  0.03621862],
       [-0.02967414,  0.01046272, -0.02641489, -0.0531544 ,  0.05461847],
       [ 0.01689683, -0.02641489, -0.01832519,  0.05849126, -0.00758004],
       [ 0.10638671, -0.0531544 ,  0.05849126, -0.00175298, -0.02274985],
       [ 0.03621862,  0.05461847, -0.00758004, -0.02274985,  0.02697974]])