In [1]:
import numpy as np

# Homework 2
Gabrial Erismann

## Exercise 1

* $A^T * B = M_{3,7}$ and $B^T * A = M_{7,3}$
* $A * C^T = M_{10,4}$ and $C*A^T = M_{4,10}$ 
* $A * e = M_{10,1}$ and $e^T*A^T = M_{1,10}$
* $A^T * f = M_{7,1}$ and $f^T*A = M_{1,7}$
* $B * d = M_{10,1}$ and $d^T*B^T = M_{1,10}$
* $B^T * f = M_{3,1}$ and $f^T*B = M_{1,3}$
* $e^T * C^T = M_{1,4}$ and $C*e = M_{4,1}$
* $d * e^T = M_{3,7}$ and $e*d^T = M_{7,3}$
* $d * f^T = M_{3,10}$ and $f*d^T = M_{10,3}$
* $f * e^T = M_{10,7}$ and $e*f^T = M_{7,§0}$

## Exercise 2
The easiest method to manually compute the determinant of the 3X3 matrix is the following:
$$det(A) = 4\begin{bmatrix} 6 & 8 \\ -3 & 2 \end{bmatrix} - 7\begin{bmatrix} -1 & 3 \\ 8 & 2 \end{bmatrix} +3\begin{bmatrix} -1 & 6 \\ 3 & -3 \end{bmatrix}$$
$$det(A) = 4*[6*2-8*(-3)]-7[(-1)*2-3*8]+3[(-1)*(-3)-6*3] = 281$$


In [2]:
v1 = [4,7,3]
v2 = [-1,6,8]
v3 = [3,-3,2]
a = np.array((v1,v2,v3))
b = np.linalg.det(a)

## Exercise 3

1) For pairwise operators (°), we have $(A°B)^T = A^T ° B^T$ (at least +,/,*)

2) The dot product `A%*%B` in R and `np.dot(A,B)` in numpy returns square matrices in both cases and in the case of $C$ returns a symmetrical matrix. 

In [3]:
v1 = [2,8,5,1]
v2 = [7,3,6,8]
v3 = [9,0,5,6]
a = np.array((v1,v2,v3))
v1 = [4,2,1,6]
v2 = [6,7,4,0]
v3 = [6,8,0,1]
b = np.array((v1,v2,v3))

In [4]:
# part 1 (addition / multiplication)
(a+b).transpose()
a.transpose() + b.transpose()
(a*b).transpose()
a.transpose() * b.transpose()

array([[ 8, 42, 54],
       [16, 21,  0],
       [ 5, 24,  0],
       [ 6,  0,  6]])

In [5]:
# part 2
c = np.dot(a,b.transpose())
print(c)
d = np.dot(a.transpose(),b)
print(d)

[[35 88 77]
 [88 87 74]
 [77 74 60]]
[[104 125  30  21]
 [ 50  37  20  48]
 [ 86  92  29  35]
 [ 88 106  33  12]]


## Exercise 4

* The values are the same for $tr(A)$ and $tr(B)$ 
* $tr(A) + tr(B) = tr(A+B)$ at first glance

In [6]:
def mytrace(x):
    return np.trace(x)

print(mytrace(c))

182


In [7]:
v1 = [2,3]
v2 = [8,6]
a = np.array((v1,v2))
v1 = [4,6]
v2 = [5,4]
b = np.array((v1,v2))

In [8]:
print(F'trace of a: {mytrace(a)}')
print(F'trace of b: {mytrace(b)}')
print(F'trace of a+b: {mytrace(a+b)}')

trace of a: 8
trace of b: 8
trace of a+b: 16
